# Generated by Django 4.1.2 on 2022-10-31 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CID", models.TextField(verbose_name="CID")),
            ],
        ),
        migrations.CreateModel(
            name="Course_enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SID", models.TextField(verbose_name="SID")),
                ("midScore", models.FloatField(verbose_name="midScore")),
                ("finalScore", models.FloatField(verbose_name="finalScore")),
                ("Score", models.FloatField(verbose_name="Score")),
                (
                    "CID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
            ],
            options={"db_table": "course_enrollment",},
        ),
    ]
